/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme.ts
 * Command: astryx theme build src/theme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

/// <reference path="./skoolie.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const skoolieTheme: DefinedTheme;
